In [1]:
import numpy as np
import pandas as pd

In [2]:
values  = pd.Series(["apple","huawei","xiaomi","vivo"]*2)
values

0     apple
1    huawei
2    xiaomi
3      vivo
4     apple
5    huawei
6    xiaomi
7      vivo
dtype: object

In [3]:
pd.unique(values)

array(['apple', 'huawei', 'xiaomi', 'vivo'], dtype=object)

In [4]:
pd.value_counts(values)

xiaomi    2
apple     2
huawei    2
vivo      2
dtype: int64

In [5]:
values = pd.Series([1,2,2,2,1,1])
dim = pd.Series(["apple","huawei"])

In [6]:
dim

0     apple
1    huawei
dtype: object

In [7]:
data = ['apple', 'huawei', 'xiaomi', 'vivo']*2
data

['apple', 'huawei', 'xiaomi', 'vivo', 'apple', 'huawei', 'xiaomi', 'vivo']

In [8]:
n = len(data)
df = pd.DataFrame({"data":data,"baske":np.arange(n),"count":np.random.randint(3,15,size = n),"weight":np.random.uniform(0,4,size=n)})
df

data  baske  count    weight
0   apple      0      3  0.454385
1  huawei      1     14  2.243383
2  xiaomi      2      9  0.342843
3    vivo      3     10  2.423088
4   apple      4     10  3.085308
5  huawei      5      5  1.742785
6  xiaomi      6     14  2.840659
7    vivo      7     11  2.789106

In [9]:
data1  = df["data"].astype("category")
data1

0     apple
1    huawei
2    xiaomi
3      vivo
4     apple
5    huawei
6    xiaomi
7      vivo
Name: data, dtype: category
Categories (4, object): [apple, huawei, vivo, xiaomi]

In [10]:
c= data1.values
c.categories

Index(['apple', 'huawei', 'vivo', 'xiaomi'], dtype='object')

In [11]:
c.code

AttributeError: 'Categorical' object has no attribute 'code'

In [12]:
c.codes

array([0, 1, 3, 2, 0, 1, 3, 2], dtype=int8)

In [13]:
df["data"] = df['data'].astype("category")
df['data']

0     apple
1    huawei
2    xiaomi
3      vivo
4     apple
5    huawei
6    xiaomi
7      vivo
Name: data, dtype: category
Categories (4, object): [apple, huawei, vivo, xiaomi]

In [14]:
my_cate = pd.Categorical(['foo','bar','baz','foo','bar'])
my_cate

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [15]:
cate = ['foo','bar','baz']

In [16]:
codes = [0,1,2,0,0,1]
my_cats_2 = pd.Categorical.from_code(codes,categories)
my_cats_2

AttributeError: type object 'Categorical' has no attribute 'from_code'

In [17]:
my_cats_2 = pd.Categorical.from_codes(codes,categories)
my_cats_2

NameError: name 'categories' is not defined

In [18]:
my_cats_2 = pd.Categorical.from_codes(codes,cate)
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [19]:
my_cats_2 = pd.Categorical.from_codes(codes,cate,ordered  = True)
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [20]:
np.random.seed(12345)
draws = np.random.randn(1000)


SyntaxError: invalid syntax (<ipython-input-20-75047fd1d279>, line 3)

In [21]:
draws[:5]

NameError: name 'draws' is not defined

In [22]:
np.random.seed(12345)
draws = np.random.randn(1000)

In [23]:
draws[:4]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ])

In [24]:
bins = pd.qcut(draws,4)
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [25]:
bins = pd.qcut(draws,4,lables=["q1",'q2','q3','q4'])
bins

TypeError: qcut() got an unexpected keyword argument 'lables'

In [26]:
bins = pd.qcut(draws,4,labels=["q1",'q2','q3','q4'])
bins

[q2, q3, q2, q2, q4, ..., q3, q2, q1, q3, q4]
Length: 1000
Categories (4, object): [q1 < q2 < q3 < q4]

In [27]:
bins.code[:10]

AttributeError: 'Categorical' object has no attribute 'code'

In [28]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [29]:
bins = pd.Series(bins,name = 'quar')
bins

0      q2
1      q3
2      q2
3      q2
4      q4
5      q4
6      q3
7      q3
8      q4
9      q4
10     q4
11     q1
12     q3
13     q3
14     q4
15     q4
16     q1
17     q2
18     q4
19     q2
20     q2
21     q3
22     q4
23     q1
24     q2
25     q3
26     q3
27     q3
28     q3
29     q4
       ..
970    q2
971    q1
972    q2
973    q4
974    q3
975    q1
976    q1
977    q2
978    q2
979    q3
980    q3
981    q1
982    q3
983    q4
984    q2
985    q4
986    q1
987    q4
988    q1
989    q3
990    q1
991    q4
992    q1
993    q4
994    q2
995    q3
996    q2
997    q1
998    q3
999    q4
Name: quar, Length: 1000, dtype: category
Categories (4, object): [q1 < q2 < q3 < q4]

In [30]:
results = (pd.Series(draws)).groupby(bins).agg(['count','min','max']).reset_index())
results

SyntaxError: invalid syntax (<ipython-input-30-e2aae777249e>, line 1)

In [31]:
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())
results

quar  count       min       max
0   q1    250 -2.949343 -0.685484
1   q2    250 -0.683066 -0.010115
2   q3    250 -0.010032  0.628894
3   q4    250  0.634238  3.927528

In [32]:
results['quar']

0    q1
1    q2
2    q3
3    q4
Name: quar, dtype: category
Categories (4, object): [q1 < q2 < q3 < q4]

In [33]:
N = 10000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))
categories = labels.astype('category')
labels.memory_usage()

80000080

In [34]:
categories.memory_usage()

10000272

In [35]:
s = pd.Series(['a','b','c','d']*2)
cats = s.astype('category')
cats

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [36]:
cats.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [37]:
cats.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [38]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2,dtype='category')
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [39]:
df = pd.DataFrame({'key':['a','d','e','g']*2,'value':np.arange(12)})
df

ValueError: arrays must all be same length

In [40]:
df = pd.DataFrame({'key':['a','d','e','g']*3,'value':np.arange(12)})
df

key  value
0    a      0
1    d      1
2    e      2
3    g      3
4    a      4
5    d      5
6    e      6
7    g      7
8    a      8
9    d      9
10   e     10
11   g     11

In [41]:
g = df.groupby('key').value
g.mean()

key
a    4
d    5
e    6
g    7
Name: value, dtype: int32

In [42]:
g.transform(lambda x: x.mean())

0     4
1     5
2     6
3     7
4     4
5     5
6     6
7     7
8     4
9     5
10    6
11    7
Name: value, dtype: int32

In [43]:
g.transform('mean')

0     4
1     5
2     6
3     7
4     4
5     5
6     6
7     7
8     4
9     5
10    6
11    7
Name: value, dtype: int32

In [44]:
g.transform(lambda x: x * 2)

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
Name: value, dtype: int32

In [45]:
g.transform(lambda x: x.rank(ascending=False))

0     3
1     3
2     3
3     3
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
Name: value, dtype: int32

In [46]:
n = 15
times = pd.date_range('2017-05-20',freq = 'lmin',periods = n)
df = pd.DataFrame({'time':times,"value":np.arange(n)})
df

ValueError: Invalid frequency: lmin

In [47]:
n = 15
times = pd.date_range('2017-05-20',freq = '1min',periods = n)
df = pd.DataFrame({'time':times,"value":np.arange(n)})
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [48]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5