In [1]:
import pandas as pd


In [2]:
from pandas import DataFrame,Series

In [3]:
obj = pd.Series([1,2,-2,34])

In [4]:
obj

0     1
1     2
2    -2
3    34
dtype: int64

In [5]:
obj.values


array([ 1,  2, -2, 34], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj = pd.Series([1,2,3,4],index = ["x","y","z","k"])

In [8]:
obj

x    1
y    2
z    3
k    4
dtype: int64

In [9]:
obj.index

Index(['x', 'y', 'z', 'k'], dtype='object')

In [10]:
obj["x"]

1

In [11]:
obj["x","y"]

KeyError: ('x', 'y')

In [12]:
obj[["x","y"]]

x    1
y    2
dtype: int64

In [13]:
obj[obj>2]

z    3
k    4
dtype: int64

In [14]:
obj+2

x    3
y    4
z    5
k    6
dtype: int64

In [15]:
obj*3

x     3
y     6
z     9
k    12
dtype: int64

In [16]:
"x" in obj

True

In [17]:
dic_data = {"jdj":90,"djjd":38,"jde":29}
obj_1 = pd.Series(dic_data)

In [18]:
obj_1

jdj     90
djjd    38
jde     29
dtype: int64

In [19]:
pd.isnull(obj_1)

jdj     False
djjd    False
jde     False
dtype: bool

In [20]:
pd.notbull(obj_1)

AttributeError: module 'pandas' has no attribute 'notbull'

In [21]:
pd.notnull(obj_1)

jdj     True
djjd    True
jde     True
dtype: bool

In [22]:
obj.isnull()

x    False
y    False
z    False
k    False
dtype: bool

In [23]:
obj.notnull

<bound method Series.notnull of x    1
y    2
z    3
k    4
dtype: int64>

In [24]:
notnull()

NameError: name 'notnull' is not defined

In [25]:
obj.notnull()

x    True
y    True
z    True
k    True
dtype: bool

In [26]:
obj.name()

TypeError: 'NoneType' object is not callable

In [27]:
obj.name

In [28]:
dic = {"jjd":[1,2,3,4,5],"jdhg":["dd","dd","ed","de","uj"]}

In [29]:
obj_4 = pd.DateFrame(dic)

AttributeError: module 'pandas' has no attribute 'DateFrame'

In [30]:
obj_4 = pd.DataFrame(dic)

In [31]:
obj_4

jjd jdhg
0    1   dd
1    2   dd
2    3   ed
3    4   de
4    5   uj

In [32]:
obj_4.head()

jjd jdhg
0    1   dd
1    2   dd
2    3   ed
3    4   de
4    5   uj

In [33]:
pd.DataFrame(dic,columns =["dabai","xiaobai"] )

Empty DataFrame
Columns: [dabai, xiaobai]
Index: []

In [34]:
dic

{'jjd': [1, 2, 3, 4, 5], 'jdhg': ['dd', 'dd', 'ed', 'de', 'uj']}

In [35]:
pd.DataFrame(dic,columns =["dabai","xiaobai"] )

Empty DataFrame
Columns: [dabai, xiaobai]
Index: []

In [36]:
pd.DataFrame(dic)

jjd jdhg
0    1   dd
1    2   dd
2    3   ed
3    4   de
4    5   uj

In [37]:
pd.DataFrame(dic,columns = ["d","s"])

Empty DataFrame
Columns: [d, s]
Index: []

In [38]:
obj_4["jjd"]

0    1
1    2
2    3
3    4
4    5
Name: jjd, dtype: int64

In [39]:
obj_4.loc("1")

ValueError: No axis named 1 for object type <class 'type'>

In [40]:
obj_4.loc(1)

In [41]:
obj_4.loc["1"]

KeyError: '1'

In [42]:
obj_4.loc[1]

jjd      2
jdhg    dd
Name: 1, dtype: object

In [43]:
obj_4["jdhgy"]=12

In [44]:
obj_4

jjd jdhg  jdhgy
0    1   dd     12
1    2   dd     12
2    3   ed     12
3    4   de     12
4    5   uj     12

In [45]:
obj_4["jdhid"] = np.arange(6)

NameError: name 'np' is not defined

In [46]:
import numpy as np

In [47]:
obj_4["jdhid"] = np.arange(6)

ValueError: Length of values does not match length of index

In [48]:
obj_4["jdhid"] = np.arange(5)

In [49]:
obj_4

jjd jdhg  jdhgy  jdhid
0    1   dd     12      0
1    2   dd     12      1
2    3   ed     12      2
3    4   de     12      3
4    5   uj     12      4

In [50]:
val = pd.Series([1,5,33,33,2],index = [0,1,2,3,4])

In [51]:
obj_4["one"] = val

In [52]:
obj_4

jjd jdhg  jdhgy  jdhid  one
0    1   dd     12      0    1
1    2   dd     12      1    5
2    3   ed     12      2   33
3    4   de     12      3   33
4    5   uj     12      4    2

In [53]:
del obj_4["one"]

In [54]:
obj_4

jjd jdhg  jdhgy  jdhid
0    1   dd     12      0
1    2   dd     12      1
2    3   ed     12      2
3    4   de     12      3
4    5   uj     12      4

In [55]:
obj_4.columns

Index(['jjd', 'jdhg', 'jdhgy', 'jdhid'], dtype='object')

In [56]:
obj_3 = obj_4

In [57]:
obj_3["jjd"]=1

In [58]:
onj_4

NameError: name 'onj_4' is not defined

In [59]:
obj_4

jjd jdhg  jdhgy  jdhid
0    1   dd     12      0
1    1   dd     12      1
2    1   ed     12      2
3    1   de     12      3
4    1   uj     12      4

In [60]:
obj_4.values

array([[1, 'dd', 12, 0],
       [1, 'dd', 12, 1],
       [1, 'ed', 12, 2],
       [1, 'de', 12, 3],
       [1, 'uj', 12, 4]], dtype=object)

In [61]:
obj_4.index()

TypeError: 'RangeIndex' object is not callable

In [62]:
obj_4.index

RangeIndex(start=0, stop=5, step=1)

In [63]:
labels = pd.index([1,2,4])

AttributeError: module 'pandas' has no attribute 'index'

In [64]:
labels = pd.Index([1,2,4])

In [65]:
obj_1 = pd.Series([1,2,3,4],index = ["a","b","c","d"])

In [66]:
obj_1.reindex([1,2,3,4])

1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [67]:
obj_1.reindex([1,2,3,4],method="ffill")

TypeError: '<' not supported between instances of 'int' and 'str'

In [1]:
obj = pd.Series(np.arange(5),index = ["a","b","c","d","e"])

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
obj = pd.Series(np.arange(5),index = ["a","b","c","d","e"])

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
obj = pd.Series(np.arange(5),index = ["a","b","c","d","e"])

In [6]:
new_obj = obj.drop(["c"])

In [7]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [8]:
obj.drop(["d","c"])

a    0
b    1
e    4
dtype: int32

In [9]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index = ["a","b","c","d"],columns = ["one","two","three","four"])

In [10]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [11]:
data.drop("one",axis = 1)

two  three  four
a    1      2     3
b    5      6     7
c    9     10    11
d   13     14    15

In [12]:
data.drop("a",axis = 0)

one  two  three  four
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [13]:
data_1 = data.drop("a",axis = 0)

In [14]:
data_1["one"]=1

In [15]:
data

one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [16]:
data.drop["a",inplace = TRUE]

SyntaxError: invalid syntax (<ipython-input-16-25576f99a7e7>, line 1)

In [17]:
data.drop("a",inplace = TRUE)

NameError: name 'TRUE' is not defined

In [18]:
data.drop("a",inplace = True)

In [19]:
data

one  two  three  four
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [20]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [21]:
obj[0:2]

a    0
b    1
dtype: int32

In [22]:
obj["a":"c"]

a    0
b    1
c    2
dtype: int32

In [23]:
obj[["a","b","c"]]

a    0
b    1
c    2
dtype: int32

In [24]:
data

one  two  three  four
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15

In [25]:
data["one"]

b     4
c     8
d    12
Name: one, dtype: int32

In [26]:
data[["one","four"]]

one  four
b    4     7
c    8    11
d   12    15

In [27]:
data[:2]

one  two  three  four
b    4    5      6     7
c    8    9     10    11

In [28]:
data[data["one"]>=8]

one  two  three  four
c    8    9     10    11
d   12   13     14    15

In [29]:
data>10

one    two  three   four
b  False  False  False  False
c  False  False  False   True
d   True   True   True   True

In [30]:
data[data>5]=0

In [31]:
data

one  two  three  four
b    4    5      0     0
c    0    0      0     0
d    0    0      0     0

In [32]:
data.loc["b",["one","two"]]

one    4
two    5
Name: b, dtype: int32

In [33]:
data.iloc[1,1:3]

two      0
three    0
Name: c, dtype: int32

In [34]:
data.loc["b":"c","one":"three"]

one  two  three
b    4    5      0
c    0    0      0

In [35]:
s1 = pd.Series([1,2,3,4],index = ["a","b","c","d"])

In [36]:
s2 = pd.Series([5,6,7,8],index = ["c","d","f","q"])
s1+s2

a     NaN
b     NaN
c     8.0
d    10.0
f     NaN
q     NaN
dtype: float64

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.arange(12).reshape(3,4)

In [3]:
data[1]

array([4, 5, 6, 7])

In [4]:
data-data[1]

array([[-4, -4, -4, -4],
       [ 0,  0,  0,  0],
       [ 4,  4,  4,  4]])

In [5]:
obj = np.array([1,2,34,3],index = ["e","f","d","s"])
obj.sort_index()

TypeError: 'index' is an invalid keyword argument for array()

In [6]:
obj = pd.Series([1,2,34,3],index = ["e","f","d","s"])
obj.sort_index()

d    34
e     1
f     2
s     3
dtype: int64

In [7]:
data_1 = pd.DataFrame(np.arange(12).reshape(3,4),columns = ["a","b","c","d"],index = ["one",])

ValueError: Shape of passed values is (3, 4), indices imply (1, 4)

In [8]:
data_1 = pd.DataFrame(np.arange(12).reshape(3,4),columns = ["a","b","c","d"],index = ["one","two","three"])

In [9]:
data_1.sort_index()

a  b   c   d
one    0  1   2   3
three  8  9  10  11
two    4  5   6   7

In [10]:
data_1.sort_index(axis = 1)

a  b   c   d
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [11]:
data_1.sort_index(axis = 1,ascending = False)

d   c  b  a
one     3   2  1  0
two     7   6  5  4
three  11  10  9  8

In [12]:
data_1.sort_index(axis = 1,ascending = True)

a  b   c   d
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [13]:
data_1.sort_values()

TypeError: sort_values() missing 1 required positional argument: 'by'

In [14]:
ata_1.sort_values(by = "b")

NameError: name 'ata_1' is not defined

In [15]:
data_1.sort_values(by = "b")

a  b   c   d
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [16]:
obj

e     1
f     2
d    34
s     3
dtype: int64

In [17]:
obj.rank()

e    1.0
f    2.0
d    4.0
s    3.0
dtype: float64

In [18]:
obj.rank(methon = "first")

TypeError: rank() got an unexpected keyword argument 'methon'

In [19]:
obj.rank(method = "first")

e    1.0
f    2.0
d    4.0
s    3.0
dtype: float64

In [20]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
data_1

a  b   c   d
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [22]:
data_1.rank(axis = "columns",method = "max")

a    b    c    d
one    1.0  2.0  3.0  4.0
two    1.0  2.0  3.0  4.0
three  1.0  2.0  3.0  4.0

In [23]:
data_1.rank(axis = "columns",method = "first")

a    b    c    d
one    1.0  2.0  3.0  4.0
two    1.0  2.0  3.0  4.0
three  1.0  2.0  3.0  4.0

In [24]:
data_1.rank(axis = "index",method = "first")

a    b    c    d
one    1.0  1.0  1.0  1.0
two    2.0  2.0  2.0  2.0
three  3.0  3.0  3.0  3.0

In [25]:
data_1.sum()

a    12
b    15
c    18
d    21
dtype: int64

In [26]:
data_1.sum(axis = "index")

a    12
b    15
c    18
d    21
dtype: int64

In [27]:
data_1.sum(axis = 1)

one       6
two      22
three    38
dtype: int64

In [28]:
data_1

a  b   c   d
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [29]:
data_1.corr()

a    b    c    d
a  1.0  1.0  1.0  1.0
b  1.0  1.0  1.0  1.0
c  1.0  1.0  1.0  1.0
d  1.0  1.0  1.0  1.0

In [30]:
data_1["a"].corr(data_1["b"])

1.0

In [31]:
data_1.cov()

a     b     c     d
a  16.0  16.0  16.0  16.0
b  16.0  16.0  16.0  16.0
c  16.0  16.0  16.0  16.0
d  16.0  16.0  16.0  16.0

In [32]:
data_1.withcorr(data_1["a"])

AttributeError: 'DataFrame' object has no attribute 'withcorr'

In [33]:
data_1.corrwith(data_1["a"])

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [34]:
obj = pd.Series(['a','d','a','c','d','r'])
obj.unique()

array(['a', 'd', 'c', 'r'], dtype=object)

In [35]:
obj.values_counts()

AttributeError: 'Series' object has no attribute 'values_counts'

In [36]:
obj.value_counts()

a    2
d    2
c    1
r    1
dtype: int64

In [37]:
obj.values()

TypeError: 'numpy.ndarray' object is not callable

In [38]:
obj.values

array(['a', 'd', 'a', 'c', 'd', 'r'], dtype=object)

In [39]:
obj.isin(["a","r"])

0     True
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [40]:
obi[obj.isin(["a","r"])]

NameError: name 'obi' is not defined

In [41]:
obj[obj.isin(["a","r"])]

0    a
2    a
5    r
dtype: object

In [42]:
data = pd.resd_csv(r"D:\Backup\桌面\测试\test.csv")

AttributeError: module 'pandas' has no attribute 'resd_csv'

In [43]:
data = pd.read_csv(r"D:\Backup\桌面\测试\test.csv")

In [44]:
data

a  b         c   d
0  1  b  20180120  23
1  2  a  20180121  24
2  3  b  20180122  25
3  4  a  20180123  26
4  5  b  20180124  27
5  6  a  20180125  28
6  7  b  20180126  29
7  8  a  20180127  30
8  9  b  20180128  31

In [45]:
pd.read_table(r"D:\Backup\桌面\测试\test.csv",seq = ",")

TypeError: parser_f() got an unexpected keyword argument 'seq'

In [46]:
pd.read_table(r"D:\Backup\桌面\测试\test.csv",sep = ",")

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a  b         c   d
0  1  b  20180120  23
1  2  a  20180121  24
2  3  b  20180122  25
3  4  a  20180123  26
4  5  b  20180124  27
5  6  a  20180125  28
6  7  b  20180126  29
7  8  a  20180127  30
8  9  b  20180128  31

In [47]:
pd.read_table(r"D:\Backup\桌面\测试\test.csv",seq = ",",nrows = 5)

TypeError: parser_f() got an unexpected keyword argument 'seq'

In [48]:
pd.read_table(r"D:\Backup\桌面\测试\test.csv",sep = ",",nrows = 5)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a  b         c   d
0  1  b  20180120  23
1  2  a  20180121  24
2  3  b  20180122  25
3  4  a  20180123  26
4  5  b  20180124  27

In [49]:
data.to_csv(r"D:\Backup\桌面\测试\test1.csv")

In [50]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
 {"name": "Katie", "age": 38,
 "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [51]:
import ison

ModuleNotFoundError: No module named 'ison'

In [52]:
import json

In [53]:
result = json.loads(obj)

In [54]:
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [55]:
asjson = json.dumps(result)

In [56]:
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [57]:
data_2 = pd.read_excel([r"D:\Backup\桌面\测试\test.xlsx"],"sheet1")

ValueError: Invalid file path or buffer object type: <class 'list'>

In [58]:
data_2 = pd.read_excel(r"D:\Backup\桌面\测试\test.xlsx","sheet1")

ValueError: Invalid file path or buffer object type: <class 'list'>

In [59]:
data_2 = pd.read_excel(r"D:\Backup\桌面\测试\test.xlsx","sheet1")

XLRDError: No sheet named <'sheet1'>

In [60]:
data_2 = pd.read_excel(r"D:\Backup\桌面\测试\test.xlsx","Sheet1")

In [61]:
data_2


变量名称    变量类型
0  overdue_avg_max  double
1  overdue_avg_avg  double
2  overdue_avg_min  double